//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dem_Telerik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class country_master
    {
        public int country_id { get; set; }
        public string country { get; set; }
        public Nullable<byte> Company_Code { get; set; }
        public Nullable<byte> Finyear_code { get; set; }
        public Nullable<byte> Created_By { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> Generated_By { get; set; }
        public Nullable<System.DateTime> Generated_Date { get; set; }
    }
}
